package org.courseregistration.dao;


public enum SearchCriteria {

    COURSE_NAME_CONTAINS,
    DEPARTMENT_EQUALS,
    SEMESTER_EQUALS,
    DAY_OF_WEEK_EQUALS,
    PROFESSOR_FIRST_NAME_CONTAINS,
    COURSE_CODE_CONTAINS,
    PROFESSOR_LAST_NAME_CONTAINS,
    PROFESSOR_LAST_NAME_EQUALS,
    PROFESSOR_FIRST_NAME_EQUALS,
    COURSE_CODE_EQUALS,
}
